# Test this without rebuilding the docker image $> docker-compose up
# Test this with rebuilding the docker image $> docker-compose up --build

version: '3.7'

services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    image: project3:latest
    container_name: peer1
    working_dir: /project3
    networks:
      # - p2pnet
      p2pnet:
       ipv4_address: 172.28.0.2
    ports:
      - 9091/udp
      - 9092/udp
      - 9093/udp
    command: java -cp target/distributed_hash_table-1.0.jar edu.rit.cs.MiniServer

  peer2:
    image: project3:latest
    container_name: peer2
    depends_on:
      - peer1
    working_dir: /project3
    networks:
      # - p2pnet
      p2pnet:
        ipv4_address: 172.28.0.3
    ports:
      - 9091/udp
      - 9092/udp
      - 9093/udp
    command: java -cp target/distributed_hash_table-1.0.jar edu.rit.cs.ServerAgent

  peer3:
    image: project3:latest
    container_name: peer3
    depends_on:
      - peer1
    working_dir: /project3/
    networks:
      # - p2pnet
      p2pnet:
        ipv4_address: 172.28.0.4
    ports:
      - 9091/udp
      - 9092/udp
      - 9093/udp
    command: java -cp target/distributed_hash_table-1.0.jar edu.rit.cs.ClientNode 172.28.0.3:9093
      
networks:
  p2pnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16